export const AdminUsersPermissions = {
  GET_ADMIN_USERS: "GET_ADMIN_USERS",
  CREATE_ADMIN_USER: "CREATE_ADMIN_USER",
  UPDATE_ADMIN_USER: "UPDATE_ADMIN_USER",
  DELETE_ADMIN_USER: "DELETE_ADMIN_USER",
};
